In [7]:
import pandas as pd

In [8]:
df=pd.read_csv("extracted_data.csv")

In [9]:
df

,Dataset,# of keys or categories,# of examples (train/dev/test),Model,Precision,Recall,F1
0,IIT-CDIP,NaN,11M/0/0,NaN,NaN,NaN,NaN
1,FUNSD,4.0,149/0/50,NaN,NaN,NaN,NaN
2,CORD,30.0,800/100/100,NaN,NaN,NaN,NaN
3,SROIE,4.0,626/0/347,NaN,NaN,NaN,NaN
4,Kleister-NDA,4.0,254/83/203,NaN,NaN,NaN,NaN
5,RVL-CDIP,16.0,320K/4K/4K,NaN,NaN,NaN,NaN
6,DocVQA,NaN,39K/5K/5K,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,BERTBASE,0.5469,0.6710,0.6026
8,NaN,NaN,NaN,UniLMv2BASE,0.6561,0.7254,0.6890
9,NaN,NaN,NaN,BERTLARGE,0.6113,0.7085,0.6563
10,NaN,NaN,NaN,UniLMv2LARGE,0.6903,0.7649,0.7257
11,NaN,NaN,NaN,LayoutLMBASE,0.7597,0.8155,0.7866
12,NaN,NaN,NaN,LayoutLMLARGE,0.7596,0.8219,0.7895
13,NaN,NaN,NaN,LayoutLMv2BASE,0.8029,0.8539,0.8276
14,NaN,NaN,NaN,LayoutLMv2LARGE,0.8324,0.8519,0.8420
15,NaN,NaN,NaN,"BROS (Hong et al., 2021)",0.8056,0.8188,0.8121